spring.application.name=paper-trading-engine

# Enable H2 Database Console in Browser
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:tradingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show the SQL statements in the IntelliJ console for debugging
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

